### ISSUE TITLE
When using #build, it will either say that the schematic was sucessfully loaded, and do nothing, or say the same, and start pathfinding somewhere random just to freeze there and stop moving (while still pathfinding)

### ISSUE THREAD

**Issue by RandomSlovak** [cabaletta/baritone#4891]
I use minecraft version 1.20.1
My version of Baritone: baritone-api-forge-1.10.3
My version of WorldEdit (that I used to make the schematic): worldedit-mod-7.2.15

I created a schematic in 1.20.1, using WorldEdit, and now it refuses to build itself.The file is .schematic, and it is in the correct folder:
C:\Users\User\AppData\Roaming\.minecraft\schematics
I set these to true:
I already set my mods to true
allowBreak
allowInventory
allowPlace
legitMine
I have all the materials needed

Is there anything I am missing?

Update: I just tried to convert the schematic to 1.12 using https://puregero.github.io/SchemToSchematic/ and it didn't work

**Comment by ZacSharp** [comment]
Have you tried using a more modern schematic format (Sponge .schem or .litematic)? The .schematic format doesn't work with any blocks added in Minecraft 1.13+ and even if WorldEdit uses a format extension to bypass that (does it?), Baritone does not implement such an extension.

**Comment by RandomSlovak** [comment]
> Have you tried using a more modern schematic format (Sponge .schem or .litematic)? The .schematic format doesn't work with any blocks added in Minecraft 1.13+ and even if WorldEdit uses a format extension to bypass that (does it?), Baritone does not implement such an extension.

Sorry for not answering for so long; I basically resolved the issue almost immediately after doing this post and forgot about it. And yes, the schematic format was the reason why it was not working. Thank you for your response, and I apologize for my late one
